name: my_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^1.3.0
  shared_preferences: ^2.1.1
  intl: ^0.18.1
  flutter_dotenv: ^5.0.2
  url_launcher: ^6.1.10
  google_fonts: ^6.1.0
  file_picker: ^5.0.0
  path: ^1.8.3
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
